### ISSUE TITLE
DE Optimiser return syntax is deprecated

### ISSUE THREAD

**Issue by drpriscu** [automl/DEHB#24]
Dear @Neeratyoy, please see the log from running the DE optimiser:

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dehb/optimizers/de.py:810: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(self.traj), np.array(self.runtime), np.array(self.history)

**Comment by Neeratyoy** [comment]
Hi
Would you like to create a PR with this change?
```python
return np.array(self.traj), np.array(self.runtime), np.array(self.history, dtype=object)
```
This should remove the warning.
If not, of course, I can update this too.

**Comment by drpriscu** [comment]
Please could you?

**Comment by Neeratyoy** [comment]
Let me know if this is making DEHB unusable and blocking your work. I'll prioritize this a bit more and get it done sooner.

**Comment by drpriscu** [comment]
Only appears when running the DE optimiser; may prevent retrieving results.

**Comment by Neeratyoy** [comment]
Thanks for the issue.
This has been updated in the `v0.0.5` PyPi release of `dehb`.
