### ISSUE TITLE
Checkpointing optimization run

### ISSUE THREAD

**Issue by Bronzila** [automl/DEHB#31]
A nice addition to the package could be checkpointing the state of the optimizer in order to restart the optimization e.g. when an optimization run has finished or crashed. 

This could also be interesting for issue #30 in order to restart the optimization with a higher computational budget.

PR #6 has already touched this topic and it might make sense to get some inspiration form there.

We could then also adjust the pytorch example to feature this.

**Comment by Neeratyoy** [comment]
Could we perhaps link this as TODOs post the ask-tell and config ID changes?

**Comment by eddiebergman** [comment]
I would add that the `tell()` part of `ask()` and `tell()` makes this functionality trivially easy for both DEHB or external users #36 .
