### ISSUE TITLE
Handling min_budget = max_budget situation

### ISSUE THREAD

**Issue by Bronzila** [automl/DEHB#33]
When specifying the minimum budget equal to the maximum budget, DEHB performs plain DE. There are two potential ways of dealing with this:

1. Break and throw an error communicating to the user, that this setup would result in plain DE and therefore it wont be done or
2. Return a warning and perform DE with a population consisting of one individual on the max_budget. However only random configs are used for mutation

Personally, I would prefer option 2, since I do not feel the need to restrict the user. However communicating, that this setup does not perform DEHB should be done.

Edit: Currently we break and throw an error. However if we skip the assertion it runs through normally --> TODO: Check what happens under the hood

**Comment by Bronzila** [comment]
Just checked what happened under the hood:
Essentially it runs DE with a population consisting of one individual on the ```max_budget```. However only random configs are used for mutation, since the parent and global pool are obviously empty, since there are no promotions from lower to higher budgets.
@Neeratyoy I don't think it makes sense to run DEHB in such a setting, but given, that it is possible, should we still allow it? If we allow it, I would obviously add a warning describing what would happen as above. What do you think?

**Comment by Neeratyoy** [comment]
Would be nice to compare what the likes of SMAC or NePS does in such cases and be consistent if possible.

**Comment by Bronzila** [comment]
When using the ```SuccessiveHalving``` and ```Hyperband``` intensifiers SMAC actually restricts the user to only use ```max_budget > min_budget``` as seen here [here](https://github.com/automl/SMAC3/blob/e64e1918eeb88e93f9f201ece343624fb2943e9d/smac/intensifier/successive_halving.py#L131C90-L131C90).
Should we stay consistent with SMAC or should I still implement the idea of running plain DE?

**Comment by Neeratyoy** [comment]
It is fair to throw a warning and halt execution if min and max budgets are the same.
We should undoubtedly give better warnings.
To be fancy, we could even dump a parameterized call to DE and suggest to the user that if they have a fixed fidelity, they can instead run DE.
