### ISSUE TITLE
Implement ask-and-tell interface for DEHB

### ISSUE THREAD

**Issue by Bronzila** [automl/DEHB#36]
Similar to [SMAC](https://automl.github.io/SMAC3/main/advanced_usage/5_ask_and_tell.html), an ask-and-tell interface would make DEHB more flexible and potentially easier to use.

**Comment by eddiebergman** [comment]
Some extra comments thinking out it's use case:
* If I `tell()` many times before starting optimization, these results are used.
* If I `tell()` during optimization but with a result that was not suggested by DEHB, how should it be used. What happens to the population? What if it's not in a fidelity bracket DEHB is aware of? If there's no good idea, better to explicitly error then.
* If I `ask()` twice without any internal update, will I get the same suggestion? Can I get two different suggestions for better parallelization?
   *`xs = [ask(), ask()]` -> Two same suggestions
   *`xs = ask(2)` -> Two different suggestions
