### ISSUE TITLE
Use of deprecated np.int in dimension type checking

### ISSUE THREAD

**Issue by Bronzila** [automl/DEHB#41]
[Here](https://github.com/automl/DEHB/blob/20a6b537cfb0cec82d31e0729cebe506e1009892/dehb/optimizers/dehb.py#L35C8-L35C8) the deprecated `np.int` type of numpy is used, when initalizing DEHB without a configspace object. This is deprecated since numpy v1.20 and should be replaced by either `np.int32` or `np.int64`.

**Comment by SandboxHead** [comment]
Hey @Bronzila I will make these required changes. Can you assign me this issue?

**Comment by eddiebergman** [comment]
Will add that the deprecation is mostly when used with `np.method(..., dtype=np.int)` as this is now made equivalent to `np.method(..., dtype=int)` and the latter should be preferred. In the case you've shown there, it's fine to check, but the best way to do instance checking right now is `isinstance(x, (int, np.integer))`. (Likewise you have `np.floating` super classes `np.float32/64`)

**Comment by Bronzila** [comment]
> Hey @Bronzila I will make these required changes. Can you assign me this issue?

@SandboxHead I will do so, thanks.
It would be great if you could have a look at our [contributing guidelines](https://github.com/automl/DEHB/blob/contributing/CONTRIBUTING.md#code-contributions). Since this is currently just a draft, it is not merged to master yet, however it should still be a good guidance.
