### ISSUE TITLE
Question about Torch version 

### ISSUE THREAD

**Issue by BLue1881euLB** [automl/DEHB#5]

**Comment by Neeratyoy** [comment]
Hi @BLue1881euLB 

May I ask to elaborate the question?

Based on the issue title, I shall mention that DEHB doesn't require or depend on `torch` to run. The function being optimized may require torch and that then depends on the user. For example, the MNIST example you'll find for DEHB uses torch and the version used to test that example is given [here](https://github.com/automl/DEHB/blob/master/examples/03_pytorch_mnist_hpo.py#L16) .

If the above clarifies your concern, please feel free to close the issue. :)
