### ISSUE TITLE
Introduce IDs for evaluated configurations

### ISSUE THREAD

**Issue by Bronzila** [automl/DEHB#62]
Some advantages of assigning an unique ID to each configuration could be:
- Better logging (e.g. better readability, result dicts for each configuration)
- Checkpointing (and restarting) an optimization run

Regarding the implementation, I would suggest using incrementing IDs. However we would need to implement a check everytime we sample/generate a new configuration, testing if it has been used before. For this check I suggest to use the vector representation of the configuration, so that both using and not using `ConfigSpace` is supported out of the box.

Using an element-wise comparison between each hyperparameter specified in the config could potentially be costly, namely `O(n*d)` if n is the number of sampled configs and d is the dimensionality of the configuration (number of hyperparameters). However since d tends to be rather small, I think this will not be a drastic computational overhead.

An alternative could be hashing the configurations and then using this hash as an ID directly, which would result in a faster comparison. However hash collisions could map different configs to the same ID.

**Comment by eddiebergman** [comment]
Just a note that `O(n*d)` is very very worst case, and you're more likely to encounter something like `O(n + 1/2*n + 1/4*n + ...) == O(2n) == O(n)` as you cut away half the possibilities with each dimension. 

More optimally in this case is use binary search. This requires some sorted structure, which in this case is tuples of length `d`. Your worse case then becomes `O(log(n)*d)` as you can binary search over `n`. You could try [`searchsorted`](https://numpy.org/doc/stable/reference/generated/numpy.searchsorted.html) from numpy and build some class/object that maintains sorted insertion order and implements the `O(log(n)*d)` lookup. If you really want to squeeze juice, you'd want to sort `d` such that the first elements have the greatest variation, therefor cutting out the most items as soon as possible (i.e. 10-valued category vs a binary category).

However this is all premature optimization, I would go with the trivial lookup, but going on dimension at a time to reduce the necessary comparisons.

**Comment by Bronzila** [comment]
Hey, I started working on some concepts to implement configuration IDs and I came to the following conclusion with some remaining questions:
I would suggest implementing a `ConfigurationRepository`, which contains all logic regarding how to assign IDs (and results) to configurations. This might currently not be too much logic, since we agreed to firstly not check for equality when assigning IDs to configurations, but maybe in the future there are more complex decisions to be made.
For now this class would mainly be interfaced by two methods:
- `announce_config(self, config: np.array, budget: float) -> int`, which announces that the given config will be evaluated on the given budget. Then this config along with the budget information will be saved in a list and the index to the list will be returned as the ID
- `tell_result(self, config_id: int, budget: float, score: float, cost: float)`. This method can be used to keep track of the score a specific configuration got on a specific budget, which could ultimately be really useful for logging.

The main question I have is regarding how we want to refactor the DEHB code to work with config IDs. I personally see 3 scenarios:
1. Each DE instance also keeps an additional list of config IDs (currently each DE instance keeps the population (configs) in a list). This could get unhandy when sorting lists/working on the lists, since we would have to make sure to perform the same operations on the ID list.
2. The DE instances do not keep configs in their population, but only config IDs. Whenever the actual config is needed (e.g. evolving or evaluating) it would then be fetched from the `ConfigRepository`.
3. The DE instances keep objects in their population. These objects would then have an attribute `id` and an attribute `config`. This would alleviate the need to take care of two lists as proposed in scenario 1 while still having "direct" access to the config itself without fetching it from the `ConfigRepository` as described in scenario 2.

I would personally prefer scenario 3, since I feel like it only needs moderate refactorings, it couples the configuration and their ID properly and it is still quite flexible for new changes.

Please feel free to comment which concept you would prefer or if you have any other ideas/features I should think about. Thanks in advance! :)
