### ISSUE TITLE
[Bug] Seeding is not applied to configspace

### ISSUE THREAD

**Issue by eddiebergman** [automl/DEHB#83]
Please see this reproducible example and output, I believe it's becuase the configspace is never seeded:

```python
from __future__ import annotations

from ConfigSpace import ConfigurationSpace

from dehb import DEHB

cs = ConfigurationSpace({"a": (1.0, 10.0)})


def f(config, fidelity):
    print(config, fidelity)
    return {"fitness": config["a"] ** 2, "cost": 1.0, "info": {}}


D = DEHB(cs, f=f, seed=1, min_fidelity=1, max_fidelity=100, n_workers=1)
D.run(1)

D = DEHB(cs, f=f, seed=1, min_fidelity=1, max_fidelity=100, n_workers=1)
D.run(1)
```

**Comment by Bronzila** [comment]
Hey,
thanks for the issue! :)
Yes this is most certainly due to us not reseeding the ConfigurationSpace, however do you think this is our job to do or shouldn't the user seed the ConfigurationSpace before passing it in? Just wondering how other libraries handle this.

**Comment by eddiebergman** [comment]
Most people don't know that they need to seed the space and I imagine they would expect if they pass a seed to DEHB then it should reproduce. Otherwise, the seed passed to DEHB has no meaning, (unless you happened to know you should also do this other thing).

Every library I've worked on that uses ConfigSpace sets the seed themselves on it for this reason.

**Comment by Bronzila** [comment]
That makes sense. Thanks for the PR, I will aim to review it by the end of the week! :)
